name: Run Cypress Tests
on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        uses: 
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          headless: true
          start: npm run start
          wait-on: "https://example.cypress.io/todo"