name: Run Cypress Tests
on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          run: npm run start
