name: Run Cypress Tests
on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start  
          browser: chrome
